# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-09 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='联系邮件')),
                ('letter', models.CharField(max_length=8, verbose_name='机房简称')),
            ],
            options={
                'db_table': 'resource_idc',
                'ordering': ['id'],
            },
        ),
    ]
