# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='mail',
            field=models.CharField(help_text='厂商邮件', max_length=32, null=True, verbose_name='联系邮件'),
        ),
    ]
