# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0002_auto_20190311_2302'),
        ('idcs', '0001_initial'),
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, max_length=20, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=20, verbose_name='子网掩码')),
            ],
            options={
                'db_table': 'resources_ip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网卡设备名')),
                ('mac', models.CharField(max_length=32, verbose_name='网卡mac地址')),
                ('remark', models.CharField(max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'resources_networkdevice',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default=None, help_text='管理IP', max_length=32, verbose_name='管理IP')),
                ('hostname', models.CharField(db_index=True, default=None, help_text='主机名', max_length=50, verbose_name='主机名')),
                ('cpu', models.CharField(default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息')),
                ('mem', models.CharField(default=None, help_text='内存信息', max_length=100, verbose_name='内存信息')),
                ('disk', models.CharField(help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息')),
                ('os', models.CharField(default=None, help_text='操作系统', max_length=100, verbose_name='操作系统')),
                ('sn', models.CharField(db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN')),
                ('rmt_card_ip', models.CharField(help_text='远程管理卡IP', max_length=15, null=True, verbose_name='远程管理卡IP')),
                ('cabinet_position', models.CharField(help_text='机柜内位置', max_length=32, null=True, verbose_name='机柜内位置')),
                ('last_check', models.DateTimeField(auto_now=True, help_text='上次检测时间', verbose_name='上次检测时间')),
                ('uuid', models.CharField(db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID')),
                ('cabinet', models.ForeignKey(help_text='所在机柜', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Cabinet', verbose_name='所在机柜')),
                ('idc', models.ForeignKey(help_text='所在机房', null=True, on_delete=django.db.models.deletion.CASCADE, to='idcs.IDC', verbose_name='所在机房')),
                ('manufacturer', models.ForeignKey(help_text='制造商', null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturers', verbose_name='制造商')),
                ('model_name', models.ForeignKey(default=None, help_text='服务器型号', on_delete=django.db.models.deletion.CASCADE, to='manufacturers.ProductModel', verbose_name='服务器型号')),
            ],
            options={
                'db_table': 'resources_server',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='所在服务器'),
        ),
        migrations.AddField(
            model_name='ip',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.NetworkDevice', verbose_name='网卡'),
        ),
    ]
